name: step_slider
description: Flutter slider widget that snaps to given step values and notifies each step change.
version: 1.0.0+1
author: Tomasz Wyrowinski <tomwyr@hotmail.com>
homepage: https://github.com/tomwyr/step-slider/

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver_hashcode: ^2.0.0
  collection: ^1.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter
